### ISSUE TITLE
a little fix on nav and hyper links

### ISSUE THREAD

**Issue by arian0zen** [PriyoRaven/MOBA#1]
hey there,
i hope you are doing well, i was saying that there is an issue on the navbar section hyperlinks, when we click on the 'moba games' it takes us to the all the moba game section as it supposed to, but on the same not, when we click on 'champion' it does not take us to the champions section on the page, i think it should take us to the 'know your champion' section.
So, i was asking if you allow me and assign me the issue i can create a pull request on the project and you should merge ?
may i ?

waiting for follow ups, thank you !!

**Comment by PriyoRaven** [comment]
Yes ofcourse you can change in the code. I will be glad to see the change.
